### ISSUE TITLE
Handling HTTPS services.

### ISSUE THREAD

**Issue by davidescobar** [devinus/detergent#12]
How do you access SOAP services that use HTTPS?

When accessing through HTTPS, I get the error:
** (MatchError) no match of right hand side value: {:error, :enoent}
     src/detergent.erl:411: :detergent.get_url_file/1

In looking at the code, it seems like only the case for HTTP is handled. Is this a missing feature, or do I need to call HTTPS services in a different way? I'm just getting familiar with the library, so not sure. Thanks.

**Comment by davidescobar** [comment]
After taking a closer look, there's already an open pull request that implements HTTPS functionality. Can it be accepted and merged in? (It's been open for 2 years).

In the meantime, for anyone else that's running into this issue, point your dependencies to this version:
https://github.com/afternoon/detergent

I've only just started using it, but it seems to work just fine. It works for both HTTP and HTTPS services.

**Comment by devinus** [comment]
Closed by https://github.com/devinus/detergent/commit/5354f1c82520666f5746aae1fbbec41331b52f4c.

**Comment by stringsn88keys** [comment]
Can this published as a 0.3.1 version to hex? As best I can tell, there's no update for this change.
